# Documentation for travis.yml can be found here
# http://about.travis-ci.org/docs/user/languages/python/


language: python
python:
  - "2.6"
  - "2.7"
env:
  - DB=sqlite://
  - DB=mysql://root:@127.0.0.1/pyconca_test
before_script:
  - pip install --use-mirrors MySQL-python
  - mysql -e 'create database pyconca_test;'
install: 
   - pip install . --use-mirrors
script: make test
notifications:
  irc: "irc.freenode.net#pyconca"
