# Documentation for travis.yml can be found here
# http://about.travis-ci.org/docs/user/languages/python/


language: python
python:
  - "2.6"
  - "2.7"
install: 
   - pip install . --use-mirrors
script: make test
notifications:
  irc: "irc.freenode.net#pyconca"
